### PR TITLE
Fix some anchor links

### PR DESCRIPTION
**Pull request by aminomancer**
The anchor links after readJSON were getting swallowed up by the readJSON heading bc of the angle brackets, probably GitHub was parsing it as an HTML tag.

### CODE REVIEW

**Comment by MrOtherGuy** [comment]
Sounds good, thanks!

Github must have changed something because I'm sure it has worked in the past... perhaps related, I've seen few occasions today where github's syntax highlighter hasn't worked correctly so maybe there's something going on in their end.

**Comment by MrOtherGuy** [comment]
> till I tried testing the startup error notification

On that note, if you think of of a specific method that will cause startup to break then please do share. I had something in the past that for sure broke startup but it seems I've lost it.

**Comment by MrOtherGuy** [comment]
I can't test this right now, but I have a feeling it might have been that simply trying to access `gURLbar` would end up initializing it. But `gBrowser` wasn't available for *it* at that time and that caused all sorts of things to fall apart.

**Comment by MrOtherGuy** [comment]
Turns out I remembered right. Having a script with simply `console.log(gURLBar.value);` breaks startup completely (and the gBrowser checking code notices it and the workaround does solve the issue like it is supposed to)

I believe what ends up happening is that we [end up here](https://searchfox.org/mozilla-central/rev/43ee5e789b079e94837a21336e9ce2420658fd19/browser/base/content/browser.js#337) and then in the UrlbarInput constructor [eventually here](https://searchfox.org/mozilla-central/rev/43ee5e789b079e94837a21336e9ce2420658fd19/browser/components/urlbar/UrlbarInput.sys.mjs#261).

I'm less certain about why that breaks startup though, since just trying to access gBrowser simply results in an error. Maybe it's because it's XPCOMUtils lazygetter that throws or something. Or just the fact that gURLBar was never constructed successfully. Regardless, it's an easy way to break startup.

**Comment by aminomancer** [comment]
Oh huh... I'll do some testing on that. I've actually been meaning to figure out a simple way to add autoconfig to local builds. I want to use my browser toolbox button script for development on mozilla-central, but all the files are removed when clobbering, and it's tedious adding them manually. I can make a shell script for it but I'm hoping to find a way to add it to mach settings somehow, so the files are added automatically when building. I guess I could add the files in a mochitest, though that wouldn't be too useful for adding my toolbox button, and the timing probably isn't right.

I found [this](https://searchfox.org/mozilla-central/source/testing/mozharness/mozharness/mozilla/firefox/autoconfig.py), but I have no idea what it's for. It doesn't seem to be referenced anywhere. I also found [this really old guide](http://web.mit.edu/~firefox/www/maintainers/autoconfig.html) which references mozconfig settings, but not settings to add autoconfig on build.

**Comment by aminomancer** [comment]
Looks like you're right though:
```
Browser is executing custom scripts via autoconfig boot.jsm:3:9
1672183870182	addons.xpi	WARN	Checking C:\mozilla-git\mozilla-central\obj-firefox\artifact\dist\bin\distribution\extensions for addons
Error: @ test.uc.js
    tryLoadIntoWindow chrome://userchromejs/content/boot.jsm:170
    onDOMContent chrome://userchromejs/content/boot.jsm:880
    handleEvent chrome://userchromejs/content/boot.jsm:937
Caused by: TypeError: can't access property "tabContainer", this.window.gBrowser is undefined
    UrlbarInput resource:///modules/UrlbarInput.sys.mjs:261
    <anonymous> chrome://browser/content/browser.js:337
    get resource://gre/modules/XPCOMUtils.sys.mjs:54
    <anonymous> chrome://userscripts/content/test.uc.js:1
    tryLoadIntoWindow chrome://userchromejs/content/boot.jsm:158
    onDOMContent chrome://userchromejs/content/boot.jsm:880
    handleEvent chrome://userchromejs/content/boot.jsm:937
boot.jsm:170:15
Uncaught TypeError: can't access property "inputField", gURLBar is undefined
    _setURLBarPlaceholder chrome://browser/content/browser.js:4044
    initPlaceHolder chrome://browser/content/browser.js:3948
    onDOMContentLoaded chrome://browser/content/browser.js:1744
browser.js:4044:1
Unknown category for SetEventRecordingEnabled: page_load
Uncaught TypeError: can't access property "updateLayoutBreakout", gURLBar is undefined
    update chrome://browser/content/browser.js:6960
    init chrome://browser/content/browser.js:6888
    onLoad chrome://browser/content/browser.js:1816
browser.js:6960:5
```

**Comment by MrOtherGuy** [comment]
You can forward prefs to `mach run` somehow, right? So, perhaps you can tell it the location of your config.js (meaning the file that is normally in the same folder where firefox binary is) - so try to store that in some fixed location outside of your build directory. If you can do that then you should be able to edit config.js to look for boot.jsm also in some other place, outside of profile directory.

**Comment by aminomancer** [comment]
Yeah I use a file [~/.mozbuild/machrc](https://firefox-source-docs.mozilla.org/mach/settings.html) to set up similar development things. But the autoconfig prefs [need to be set on the default branch](https://searchfox.org/mozilla-central/rev/4c86c51a4fedf5569c948225984f8fe26713dbe4/extensions/pref/autoconfig/src/nsReadConfig.cpp#150), and mozbuild settings are just read into user prefs at startup. But even if I knew a way to make default prefs without modifying the source code, the autoconfig code itself [takes the filename](https://searchfox.org/mozilla-central/rev/4c86c51a4fedf5569c948225984f8fe26713dbe4/extensions/pref/autoconfig/src/nsReadConfig.cpp#196) and [specifically looks for it in the binary root folder](https://searchfox.org/mozilla-central/rev/4c86c51a4fedf5569c948225984f8fe26713dbe4/extensions/pref/autoconfig/src/nsReadConfig.cpp#253). So it seems not possible to set an absolute path for `general.config.filename` unfortunately.

So, I've been assuming the only way is to configure the build settings somehow. It's probably just impossible, so I haven't spent any serious time on this, but I figure there just might have been some build automation tools designed for enterprise customers at some point. And it would make life so much easier. I'm considering just trying to get the toolbox button added to firefox and enabled only by pref or only in local builds or something. But still would be great to be able to run tests on autoconfig

**Comment by MrOtherGuy** [comment]
Huh. Okay, I'm certain I've read something about where the config.js could actually be a remote file, like accessed via network. It was probably an article about centralized config management, but I stumbled on it several years back so I can't remember. And even then it was probably written even further back (possibly at netscape days even).

**Comment by aminomancer** [comment]
Hmm maybe it's this?

https://searchfox.org/mozilla-central/rev/4c86c51a4fedf5569c948225984f8fe26713dbe4/extensions/pref/autoconfig/src/nsAutoConfig.cpp#164

`autoadmin.global_config_url`

**Comment by MrOtherGuy** [comment]
Yeah, that looks familiar. So assuming that it actually works and config loaded that way behaves like config.js in binary folder, you can perhaps give it a file:// uri and see what happens? Or have a local server running though file uri is certainly easier if it works.

**Comment by aminomancer** [comment]
This one seems to accept user prefs, but it looks like the resulting input stream is [not executed in a privileged context](https://searchfox.org/mozilla-central/rev/4c86c51a4fedf5569c948225984f8fe26713dbe4/extensions/pref/autoconfig/src/nsAutoConfig.cpp#113-114). However... I think that does give me access to the prefcalls.js API, which has a defaultPref function, which I could use to set the usual prefs in the default branch. I'd still need a way to write the config.js file to the bin folder though.

**Comment by MrOtherGuy** [comment]
I kinda doubt that would work actually. It seems to me like the local config file (or lack of there of) has already been determined by the time the remote autoadmin file is evaluated [since it's the last thing in nsReadConfig::nsReadConfigFile()](https://searchfox.org/mozilla-central/rev/4c86c51a4fedf5569c948225984f8fe26713dbe4/extensions/pref/autoconfig/src/nsReadConfig.cpp#224) so even if you manage to set the default pref from remote autoadmin script the privileged file won't be executed since it's called earlier in that function.

**Comment by aminomancer** [comment]
ah you're right. I think I'll just write a shell script and put it in an alias for `mach build`

**Pull request merged**
