### PR TITLE
Add initial TypeScript types

### LINKED ISSUE #55: TypeScript types
like this for firefox globals: https://searchfox.org/mozilla-central/source/tools/@types
it may be able to provide:
- editor autocompletions (provided it's installed like the link above probably ?)
- easier to digest api docs, at least for me, as it'll include method return types, etc.

I can make a quick PR to see what it's like, etc.

### PR DESCRIPTION
**Pull request by ricewind012**
closes #55 

some stuff is "any" because these are gecko types or other firefox stuff or whatever

### CODE REVIEW

**Comment by MrOtherGuy** [comment]
This is great work, thanks a lot!
These will surely be appreciated by anyone using TypeScript to write their scripts.

Is there a reason why `UC_API.FileSystem` is tagged with `UC_FileSystem` type though? Perhaps to prevent confusion with FileSystem web API?

**Comment by ricewind012** [comment]
> Perhaps to prevent confusion with FileSystem web API?

yes

**Comment by MrOtherGuy** [comment]
Right, I couldn't get autocompletions to show up in in VS Code except after switching the filename to .ts - that's probably more about me not doing something right as I don't normally use VS Code nor typescript so I'm not super familiar with how these should be set up.

But that's besides the point, the type definitions themselves are great!

**Comment by ricewind012** [comment]
> Right, I couldn't get autocompletions to show up in in VS Code except after switching the filename to .ts - that's probably more about me not doing something right as I don't normally use VS Code nor typescript so I'm not super familiar with how these should be set up.

I should have probably written instructions on how to first. You have to first install the types (only like this, since it's private):
```
cd types
npm pack --pack-destination=..
```
then your package.json should be:
```
{
	"dependencies": {
		"@types/fx-autoconfig": "file:types-fx-autoconfig-1.0.0.tgz"
	}
}
```
and after this it should work:
```
npm i
```

note that it only works with this and not chrome/resource uris (unless there is a way to define globals with jsdoc):
```js
const { FileSystem, Utils } = window.UC_API;
```

I did the exact same thing for gecko types: https://github.com/ricewind012/firefox-fm/blob/master/scripts/download_gecko_types

**Comment by MrOtherGuy** [comment]
I got VSCode to recognize autocompletions by just dropping `tsconfig.json`, `index.d.ts` as well as `api/` directory straight into `chrome` directory. It will complain that tsconfig.json `"Cannot find type definition file for 'fx-autoconfig'."` but apparently it works fine (for autocompletion purposes anyway). No package.json required or anyhing.

Honestly I'm such a noob when it comes to ts that I have no idea how this is supposed to work and the docs I've found haven't been particularly clear about it.

This certainly isn't the first time I've stumbled into this issue with regards to ts. Like, I want to like it and types would be super helpful but every time I find that setting things up is just such a hassle with no clear documentation about what I'm supposed to do that in the end I've just stuck to vanilla js - much simpler and just works. ...in mysterious ways as js tends to do.

Regardless, this was fantastic work on your end, so thanks a bunch!

**Comment by ricewind012** [comment]
ty, I just copy pasted the readme

**Pull request merged**
